name: "stop_machine"
on:
  workflow_dispatch:

concurrency:
  group: workflow_test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  stop_machine:
    runs-on: ubuntu-latest
    name: Tun off the Oracle VM
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }} 
      OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Oci
        run: pip install oci
        
      - name: Running script (START)
        run: python3 oracle_con.py --stop --instance_id $OCI_INSTANCE_ID
      